Repository udplabs/udp-mobile, pull requests merged in 2021-08, with the labels that each got.

#3 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, enhancement

#14 Add ID Token to Scope and Store in Storage
  src/screens/CustomWebView.js
  src/screens/LoginScreen.js
Labels: type: feature

#19 Create manual.yml
  .github/workflows/pull-request-label.yml
Labels: type: maintenance

#20 Add visible feature with CustomWebView
  src/screens/CustomWebView.js
  src/screens/ProfileScreen.js
Labels: type: bug
